### PR TITLE
Add unit tests to existing functionality

### PR DESCRIPTION
**Pull request by ArturAssisComp**
This pull request adds unit tests to the repository. 
It is related to the issue: [Implement unit tests #44.]
Until now, unit tests were added to the constructor (something like a smoke test), to some static functions, and to the isRunning getter.

### CODE REVIEW

**Comment by ArturAssisComp** [comment]
I will continue to add unit tests to this PR, but I would like to make it clear if the issue [_stopWatchTimer.isRunning always false #43] is really a bug, because I could not find it while implementing unit tests for the getter isRunning.

**Comment by hukusuke1007** [comment]
Thank you for PR. But it failed unit test.

```
package:matcher                         expect
test/stop_watch_timer_test.dart 317:19  main.<fn>.<fn>.<fn>.<fn>

Expected: '00:00'
  Actual: '0000'
   Which: is different.
          Expected: 00:00
            Actual: 0000
                      ^
           Differ at offset 2

package:matcher                         expect
test/stop_watch_timer_test.dart 317:19  main.<fn>.<fn>.<fn>.<fn>

Expected: '30h 24'
  Actual: '3024'
   Which: is different.
          Expected: 30h 24
            Actual: 3024
                      ^
           Differ at offset 2

package:matcher                         expect
test/stop_watch_timer_test.dart 317:19  main.<fn>.<fn>.<fn>.<fn>

Expected: '30:41min 98'
  Actual: '30:4198'
   Which: is different.
          Expected: 30:41min 98
            Actual: 30:4198
                         ^
           Differ at offset 5

package:matcher                         expect
test/stop_watch_timer_test.dart 317:19  main.<fn>.<fn>.<fn>.<fn>

Expected: '30h 24.98'
  Actual: '3024.98'
   Which: is different.
          Expected: 30h 24.98
            Actual: 3024.98
                      ^
           Differ at offset 2

package:matcher                         expect
test/stop_watch_timer_test.dart 317:19  main.<fn>.<fn>.<fn>.<fn>

Expected: '1841min 98'
  Actual: '184198'
   Which: is different.
          Expected: 1841min 98
            Actual: 184198
                        ^
           Differ at offset 4

package:matcher                         expect
test/stop_watch_timer_test.dart 317:19  main.<fn>.<fn>.<fn>.<fn>

Expected: '30:24s '
  Actual: '3024'
   Which: is different.
          Expected: 30:24s 
            Actual: 3024
                      ^
           Differ at offset 2

package:matcher                         expect
test/stop_watch_timer_test.dart 317:19  main.<fn>.<fn>.<fn>.<fn>

Expected: '1841:98'
  Actual: '184198'
   Which: is different.
          Expected: 1841:98
            Actual: 184198
                        ^
           Differ at offset 4

package:matcher                         expect
test/stop_watch_timer_test.dart 317:19  main.<fn>.<fn>.<fn>.<fn>

Expected: '2501999792h 59min 99'
  Actual: '2501999792h 5999'
   Which: is different.
          Expected: ... 999792h 59min 99
            Actual: ... 999792h 5999
                                  ^
           Differ at offset 14

package:matcher                         expect
test/stop_watch_timer_test.dart 317:19  main.<fn>.<fn>.<fn>.<fn>

Expected: '250199979259:'
  Actual: '250199979259'
   Which: is different. Both strings start the same, but the actual value is missing the following trailing characters: :

package:matcher                         expect
test/stop_watch_timer_test.dart 317:19  main.<fn>.<fn>.<fn>.<fn>

Expected: '2501999792h 0099'
  Actual: '25019997920099'
   Which: is different.
          Expected: 2501999792h 0099
            Actual: 25019997920099
                              ^
           Differ at offset 10

package:matcher                         expect
test/stop_watch_timer_test.dart 317:19  main.<fn>.<fn>.<fn>.<fn>

Expected: '30hours'
  Actual: '30'
   Which: is different. Both strings start the same, but the actual value is missing the following trailing characters: hours
```

**Comment by ArturAssisComp** [comment]
Sorry, I should have opened this pull request as draft. I am still working on it. I will fix the test cases that fail and add more test cases.

**Comment by ArturAssisComp** [comment]
This pull request is done. It implements tests for some of the functionalities of the library. Most of the code implemented is test code. The only change made on the code of the library is related to the dispose function. Basically, it closes the _elapsedTime stream before the other streams to avoid a very specific bug that happens in test cases like the following when the command `flutter test` is used. This bug does not happen when `dart test` is used or when the subscription is cancelled before closing the stream.
```dart
import 'package:rxdart/rxdart.dart';
import 'package:stop_watch_timer/stop_watch_timer.dart';
import 'package:test/test.dart';


void main(){
  test('Should get updated second time values for count up timer ',
          () async {
// set up
        final secondTimeValues = <int>[];
        var timesChanged = 0;
        final countUp =
        StopWatchTimer(onChangeRawSecond: (_) => timesChanged++);
        final secondTimeSubscription =
        countUp.secondTime.doOnData(secondTimeValues.add).listen(null);

// initial check
        await Future<void>.delayed(Duration.zero);
        expect(secondTimeValues.length, equals(1));
        expect(secondTimeValues.last, equals(0));
        expect(timesChanged, equals(0));

// act
        countUp.onStartTimer();

// check: 0 ms
        await Future<void>.delayed(Duration.zero);
        expect(secondTimeValues.last, equals(0));
        expect(timesChanged, equals(secondTimeValues.length - 1));

// check: 500 ms
        await Future<void>.delayed(const Duration(milliseconds: 500));
        expect(secondTimeValues.last, equals(0));
        expect(timesChanged, equals(secondTimeValues.length - 1));

// check: 1050 ms
        await Future<void>.delayed(const Duration(milliseconds: 550));
        expect(secondTimeValues.last, equals(1));
        expect(timesChanged, equals(secondTimeValues.length - 1));

// check: 3050 ms
        await Future<void>.delayed(const Duration(seconds: 2));
        expect(secondTimeValues.last, equals(3));
        expect(timesChanged, equals(secondTimeValues.length - 1));

// tear down
        await countUp.dispose();
        await secondTimeSubscription.cancel();
      });

}

```
Error message
```PS
PS C:\Users\artur\Desktop\tmp\stop_watch_timer\test> flutter test .\test.dart
Changing current working directory to: C:\Users\artur\Desktop\tmp\stop_watch_timer
00:03 +0 -1: Should get updated second time values for count up timer  [E]
  Bad state: Cannot add new events after calling close
  dart:async                                            _BroadcastStreamController.add
  package:rxdart/src/subjects/subject.dart 151:17       Subject._add
  package:rxdart/src/subjects/subject.dart 141:5        Subject.add
  package:stop_watch_timer/stop_watch_timer.dart 57:26  new StopWatchTimer.<fn>
  ===== asynchronous gap ===========================
  dart:async                                            StreamView.listen
  package:stop_watch_timer/stop_watch_timer.dart 56:18  new StopWatchTimer
  test\test.dart 14:9                                   main.<fn>
  

To run this test again: C:\Users\artur\Desktop\DigitalProducts\DreamDeep\src\flutter_windows_3.7.8-stable\flutter\bin\cache\dart-sdk\bin\dart.exe test C:/Users/artur/Desktop/tmp/stop_watch_timer/test/test.dart -p vm --plain-name "Should get updated second time values for count up timer "
00:03 +0 -1: Some tests failed.
```

**Comment by ArturAssisComp** [comment]
If this PR is ok, I will start the second one, adding other test cases making more changes to the implementation. One example is the minor bug that happens when the preset time is changed dynamically, with the clock stopped.

**Review by hukusuke1007 — APPROVED** [review]
Thank you for PR!
LGTM

**Pull request merged**
